issues:
  exclude-rules:
    - path: _test\.go
      linters:
        # disabled manually
        - funlen
        - paralleltest
        - testpackage
linters-settings:
  gocritic:
    disabled-checks:
      - newDeref
linters:
  enable-all: true
  disable:
    # deprecated
    - exhaustivestruct
    - maligned
    - interfacer
    - golint
    - scopelint
    # suppress warning; xxx is disabled because of go1.18
    - bodyclose
    - contextcheck
    - interfacer
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - tparallel
    - unparam
    - wastedassign
    # disabled manually
    - godot
    - goerr113
    - gomnd
    - ireturn
    - nlreturn
    - wrapcheck
    - wsl
