name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install golangci-lint
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.46.2

    - name: Lint
      run: |
        golangci-lint run -v

    - name: Lint (manioctypechecker)
      run: |
        golangci-lint run -v
      working-directory: ./linter/manioctypechecker

    - name: Test
      run: |
        go test -v -race -failfast -coverpkg=./... -coverprofile=coverage.out ./...

    - name: Test (manioctypechecker)
      run: |
        make test
      working-directory: ./linter/manioctypechecker

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
